name = "LibraryAugmentedSymbolicRegression"
uuid = "158930c3-947c-4174-974b-74b39e64a28f"
authors = ["AtharvaSehgal <atharva.sehgal@gmail.com>", "AryaGrayeli <arya.grayeli@gmail.com>", "MilesCranmer <miles.cranmer@gmail.com>"]
version = "0.4.0"

[deps]
DispatchDoctor = "8d63f2c5-f18a-4cf2-ba9d-b3f60fc568c8"
DynamicExpressions = "a40a106e-89c9-4ca8-8020-a735e8728b6b"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
PromptingTools = "670122d1-24a8-4d70-bfce-740807c42192"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SymbolicRegression = "8254be44-1295-4e6a-a16d-46603ac705cb"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
DispatchDoctor = "^0.4.17"
DynamicExpressions = "^1, 2"
JSON = "0.21"
Logging = "1"
PromptingTools = "0.94"
Random = "<0.0.1, 1"
SymbolicRegression = "2.0"
UUIDs = "1"
julia = "1.11 - 1.12"

[sources]
SymbolicRegression = { url = "https://github.com/MilesCranmer/SymbolicRegression.jl.git", rev = "v2.0.0-beta.2" }
