name: CI

on:
  push:
    branches:
      - master
    paths:
      - "**"
  pull_request:
    branches:
      - master
    paths:
      - "**"
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  test:
    name: Julia ${{ matrix.julia-version }}-${{ matrix.os }}-${{ matrix.test }}-${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        test:
          - "online"
        julia-version:
          - "1.11"
          - "1"
        os:
          - ubuntu-latest
        include:
          - os: windows-latest
            julia-version: "~1.11.0-0"
            test: "online"
          - os: macOS-latest
            julia-version: "~1.11.0-0"
            test: "online"
          - os: ubuntu-latest
            julia-version: "~1.11.0-0"
            test: "online"
    steps:
      - uses: actions/checkout@v4
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.julia-version }}
      - name: "Cache dependencies"
        uses: julia-actions/cache@v2
        with:
          cache-name: julia-cache;workflow=${{ github.workflow }};job=${{ github.job }};os=${{ matrix.os }};julia=${{ matrix.julia-version }};project=${{ hashFiles('**/Project.toml') }}
      - name: "Build package"
        uses: julia-actions/julia-buildpkg@v1
      - name: "Run tests"
        env:
          SYMBOLIC_REGRESSION_TEST_SUITE: ${{ matrix.test }}
        run: |
          julia --color=yes -e 'import Pkg; Pkg.add("Coverage")'
          julia --color=yes --threads=auto --check-bounds=yes --depwarn=yes --code-coverage=user -e 'import Pkg; Pkg.activate("."); Pkg.test(coverage=true)'
          julia --color=yes coverage.jl
        shell: bash
      - name: "Upload coverage artifacts"
        uses: actions/upload-artifact@v7
        with:
          name: coverage-${{ matrix.os }}-${{ strategy.job-index }}
          path: lcov.info
          retention-days: 1

  upload-coverage:
    name: Upload Coverage to Codecov
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Download all coverage artifacts"
        uses: actions/download-artifact@v8
        with:
          pattern: coverage-*
          path: coverage
      - name: "Upload to Codecov"
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage
          fail_ci_if_error: ${{ secrets.CODECOV_TOKEN != '' }}
          verbose: true
